name: Bug report
description: Report a bug in Pass Alarm
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. For alarm apps, device/OS settings matter a lot.
        Please fill in the required fields.

  - type: input
    id: app_version
    attributes:
      label: App version / commit
      placeholder: "e.g., 1.0.0 (official) or commit hash"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device model
      placeholder: "e.g., iPhone 15 Pro / Pixel 8"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS version
      placeholder: "e.g., iOS 18.x / Android 15"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - iOS
        - Android
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps so we can reproduce.
      placeholder: "1) ... 2) ... 3) ..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: dropdown
    id: notif_permission
    attributes:
      label: Notification permission enabled?
      options:
        - "Yes"
        - "No"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Attach logs if possible.
