name: PassAlarm
options:
  bundleIdPrefix: com.nogeass
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: false

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: "7.0.0"
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: "11.0.0"

targets:
  PassAlarm:
    type: application
    platform: iOS
    sources:
      - path: PassAlarm
        excludes:
          - "**/.DS_Store"
    resources:
      - path: PassAlarm/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nogeass.passalarm
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: "パスアラーム"
        SWIFT_STRICT_CONCURRENCY: complete
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: true
    dependencies:
      - package: GRDB
        product: GRDB
      - package: firebase-ios-sdk
        product: FirebaseAnalytics
      - package: firebase-ios-sdk
        product: FirebaseCrashlytics

  PassAlarmTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PassAlarmTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: PassAlarm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nogeass.passalarm.tests
        GENERATE_INFOPLIST_FILE: true
